cat > docker-compose.yml <<'EOF'
version: "3"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "changeme"   # change later
      GENERIC_TIMEZONE: "America/Chicago"
    volumes:
      - ./n8n:/home/node/.n8n               # keeps flows in git
EOF


cat > docker-compose.yml

~project
